// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ms.MainApi.Entity.Contexts;

#nullable disable

namespace ms.MainApi.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20240401064924_AddOrganizationPictureTables")]
    partial class AddOrganizationPictureTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Baskets.BasketProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("productId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("BasketProducts");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Baskets.BasketProject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("projectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("projectId");

                    b.HasIndex("userId");

                    b.ToTable("BasketProjects");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Catalogs.Catalog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("properties")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Favourites.FavouriteProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("productId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.HasIndex("userId");

                    b.ToTable("FavouriteProducts");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Favourites.FavouriteProject", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("projectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("projectId");

                    b.HasIndex("userId");

                    b.ToTable("FavouriteProjects");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Identity.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<List<int>>("actions")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("permissionId")
                        .HasColumnType("integer");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("roleId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Identity.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = 0,
                            deletedBy = 0,
                            description = "Admin users role",
                            isDeleted = false,
                            name = "Admin",
                            updatedBy = 0
                        });
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Identity.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fileName")
                        .HasColumnType("text");

                    b.Property<string>("filePath")
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<string>("middleName")
                        .HasColumnType("text");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("regDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("securityStamp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = 0,
                            deletedBy = 0,
                            email = "itedu.kz@gmail.com",
                            firstName = "Алмат",
                            isActive = true,
                            isDeleted = false,
                            lastName = "Тажіхан ұлы",
                            passwordHash = "202cb962ac59075b964b07152d234b70",
                            phoneNumber = "87472203400",
                            regDate = new DateTime(2024, 4, 1, 11, 49, 23, 817, DateTimeKind.Local).AddTicks(7346),
                            updatedBy = 0
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            createdBy = 0,
                            deletedBy = 0,
                            email = "pin@gmail.com",
                            firstName = "Айнұр",
                            isActive = true,
                            isDeleted = false,
                            lastName = "Бердикул",
                            passwordHash = "202cb962ac59075b964b07152d234b70",
                            phoneNumber = "8747",
                            regDate = new DateTime(2024, 4, 1, 11, 49, 23, 817, DateTimeKind.Local).AddTicks(7385),
                            updatedBy = 0
                        });
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Identity.UserRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("roleId");

                    b.HasIndex("userId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Organizations.City", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Organizations.Organization", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("cityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("logoFileName")
                        .HasColumnType("text");

                    b.Property<string>("logoFilePath")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("phoneNumber")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("regDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("cityId");

                    b.HasIndex("userId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Organizations.OrganizationPicture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("organizationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("organizationId");

                    b.ToTable("OrganizationPictures");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Picture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Products.Brand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Products.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Products.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("brandId")
                        .HasColumnType("integer");

                    b.Property<int>("catalogId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("colorsId")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<decimal>("height")
                        .HasColumnType("numeric");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("length")
                        .HasColumnType("numeric");

                    b.Property<List<int>>("materialsId")
                        .HasColumnType("integer[]");

                    b.Property<int>("measureType")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("price")
                        .HasColumnType("numeric");

                    b.Property<int>("productArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("properties")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("width")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.HasIndex("catalogId");

                    b.HasIndex("productArticleId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Products.ProductArticle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("catalogId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("catalogId");

                    b.ToTable("ProductArticles");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Products.ProductPicture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("isMain")
                        .HasColumnType("boolean");

                    b.Property<bool>("isProcessed")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("picture")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("productId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.ToTable("ProductPictures");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Projects.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<int>>("colorsId")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<decimal>("height")
                        .HasColumnType("numeric");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("length")
                        .HasColumnType("numeric");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("price")
                        .HasColumnType("numeric");

                    b.Property<int>("projectCatalogId")
                        .HasColumnType("integer");

                    b.Property<string>("properties")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("quadrature")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("width")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("projectCatalogId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Projects.ProjectCatalog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("ProjectCatalogs");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Projects.ProjectPicture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("isMain")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("picture")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("projectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("projectId");

                    b.ToTable("ProjectPictures");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Baskets.BasketProduct", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Products.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Identity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Baskets.BasketProject", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Projects.Project", "project")
                        .WithMany()
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Identity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Favourites.FavouriteProduct", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Products.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Identity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Favourites.FavouriteProject", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Projects.Project", "project")
                        .WithMany()
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Identity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Identity.Permission", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Identity.Role", "role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Identity.UserRole", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Identity.Role", "role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Identity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Organizations.Organization", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Organizations.City", "city")
                        .WithMany()
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Identity.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Organizations.OrganizationPicture", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Organizations.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organization");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Products.Product", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Products.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Catalogs.Catalog", "catalog")
                        .WithMany()
                        .HasForeignKey("catalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Products.ProductArticle", "productArticle")
                        .WithMany()
                        .HasForeignKey("productArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");

                    b.Navigation("catalog");

                    b.Navigation("productArticle");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Products.ProductArticle", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Catalogs.Catalog", "catalog")
                        .WithMany()
                        .HasForeignKey("catalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("catalog");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Products.ProductPicture", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Products.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Projects.Project", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Projects.ProjectCatalog", "projectCatalog")
                        .WithMany()
                        .HasForeignKey("projectCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("projectCatalog");
                });

            modelBuilder.Entity("ms.MainApi.Entity.Models.DbModels.Projects.ProjectPicture", b =>
                {
                    b.HasOne("ms.MainApi.Entity.Models.DbModels.Projects.Project", "project")
                        .WithMany()
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("project");
                });
#pragma warning restore 612, 618
        }
    }
}
